/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculusprogram;


import javax.swing.JOptionPane;
/**
 *
 * @author Andry Kwiatow
 */
public class GUI extends javax.swing.JFrame {
    
    Operation newOperation; 
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        newOperation = new Operation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOneN = new javax.swing.JButton();
        btnTwoN = new javax.swing.JButton();
        btnFourN = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btnSixN = new javax.swing.JButton();
        btnFiveN = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        btnEightN = new javax.swing.JButton();
        btnSevenN = new javax.swing.JButton();
        btnThreeN1 = new javax.swing.JButton();
        btnExponent = new javax.swing.JButton();
        btnSubstract = new javax.swing.JButton();
        btnIntegral = new javax.swing.JButton();
        btnRoot = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        listVariable = new javax.swing.JList();
        txtDisplayOp = new javax.swing.JTextField();
        JCFunction = new javax.swing.JComboBox();
        btnSum = new javax.swing.JButton();
        btnProduct = new javax.swing.JButton();
        btnCloseOperator = new javax.swing.JButton();
        btnNineN1 = new javax.swing.JButton();
        txtDisplay = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Integrals Software");
        setBackground(new java.awt.Color(102, 102, 102));
        setBounds(new java.awt.Rectangle(250, 250, 450, 200));
        setMinimumSize(new java.awt.Dimension(450, 330));
        getContentPane().setLayout(null);

        btnOneN.setText("1");
        btnOneN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneNActionPerformed(evt);
            }
        });
        getContentPane().add(btnOneN);
        btnOneN.setBounds(20, 130, 77, 32);

        btnTwoN.setText("2");
        btnTwoN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoNActionPerformed(evt);
            }
        });
        getContentPane().add(btnTwoN);
        btnTwoN.setBounds(100, 130, 77, 32);

        btnFourN.setText("4");
        btnFourN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourNActionPerformed(evt);
            }
        });
        getContentPane().add(btnFourN);
        btnFourN.setBounds(20, 170, 77, 32);

        btnDivide.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnDivide.setText("/");
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });
        getContentPane().add(btnDivide);
        btnDivide.setBounds(370, 160, 50, 40);

        btnSixN.setText("6");
        btnSixN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSixNActionPerformed(evt);
            }
        });
        getContentPane().add(btnSixN);
        btnSixN.setBounds(180, 170, 77, 32);

        btnFiveN.setText("5");
        btnFiveN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiveNActionPerformed(evt);
            }
        });
        getContentPane().add(btnFiveN);
        btnFiveN.setBounds(100, 170, 77, 32);

        btnZero.setText("0");
        btnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroActionPerformed(evt);
            }
        });
        getContentPane().add(btnZero);
        btnZero.setBounds(20, 250, 77, 32);

        btnEightN.setText("8");
        btnEightN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEightNActionPerformed(evt);
            }
        });
        getContentPane().add(btnEightN);
        btnEightN.setBounds(100, 210, 77, 32);

        btnSevenN.setText("7");
        btnSevenN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSevenNActionPerformed(evt);
            }
        });
        getContentPane().add(btnSevenN);
        btnSevenN.setBounds(20, 210, 77, 32);

        btnThreeN1.setText("3");
        btnThreeN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThreeN1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnThreeN1);
        btnThreeN1.setBounds(180, 130, 77, 32);

        btnExponent.setText("x^y");
        btnExponent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExponentActionPerformed(evt);
            }
        });
        getContentPane().add(btnExponent);
        btnExponent.setBounds(370, 200, 50, 40);

        btnSubstract.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnSubstract.setText("-");
        btnSubstract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubstractActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubstract);
        btnSubstract.setBounds(320, 160, 50, 40);

        btnIntegral.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnIntegral.setText("∫");
        btnIntegral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntegralActionPerformed(evt);
            }
        });
        getContentPane().add(btnIntegral);
        btnIntegral.setBounds(270, 120, 100, 40);

        btnRoot.setText("√");
        btnRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRootActionPerformed(evt);
            }
        });
        getContentPane().add(btnRoot);
        btnRoot.setBounds(270, 200, 100, 40);

        btnEqual.setText("=");
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });
        getContentPane().add(btnEqual);
        btnEqual.setBounds(100, 250, 320, 32);

        listVariable.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "dx\t", "dy" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listVariable.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listVariableValueChanged(evt);
            }
        });
        getContentPane().add(listVariable);
        listVariable.setBounds(380, 40, 30, 40);
        getContentPane().add(txtDisplayOp);
        txtDisplayOp.setBounds(20, 30, 40, 90);
        txtDisplayOp.setEditable(false);

        JCFunction.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "∫ x^n", "∫ ax^n" }));
        JCFunction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCFunctionActionPerformed(evt);
            }
        });
        getContentPane().add(JCFunction);
        JCFunction.setBounds(270, 40, 90, 26);

        btnSum.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnSum.setText("+");
        btnSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumActionPerformed(evt);
            }
        });
        getContentPane().add(btnSum);
        btnSum.setBounds(270, 160, 50, 40);

        btnProduct.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnProduct.setText("*");
        btnProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductActionPerformed(evt);
            }
        });
        getContentPane().add(btnProduct);
        btnProduct.setBounds(370, 121, 50, 40);

        btnCloseOperator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow-right-circle (1).png"))); // NOI18N
        btnCloseOperator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseOperatorActionPerformed(evt);
            }
        });
        getContentPane().add(btnCloseOperator);
        btnCloseOperator.setBounds(347, 90, 70, 32);

        btnNineN1.setText("9");
        btnNineN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNineN1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnNineN1);
        btnNineN1.setBounds(180, 210, 77, 32);
        getContentPane().add(txtDisplay);
        txtDisplay.setBounds(60, 30, 190, 90);
        txtDisplayOp.setEditable(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
          txtDisplayOp.setText(txtDisplayOp.getText() + '/');
    }//GEN-LAST:event_btnDivideActionPerformed

    private void btnThreeN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThreeN1ActionPerformed
        txtDisplay.setText(txtDisplay.getText() + '3');
    }//GEN-LAST:event_btnThreeN1ActionPerformed

    private void btnExponentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExponentActionPerformed
          txtDisplayOp.setText(txtDisplayOp.getText() + '^');
    }//GEN-LAST:event_btnExponentActionPerformed

    private void btnSubstractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubstractActionPerformed
        txtDisplayOp.setText(txtDisplayOp.getText() + '-');
    }//GEN-LAST:event_btnSubstractActionPerformed

    private void btnIntegralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntegralActionPerformed
          txtDisplayOp.setText(txtDisplayOp.getText() + '+');
    }//GEN-LAST:event_btnIntegralActionPerformed

    private void btnRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRootActionPerformed
         txtDisplayOp.setText(txtDisplayOp.getText() + '√');
    }//GEN-LAST:event_btnRootActionPerformed

    private void listVariableValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listVariableValueChanged
        
    }//GEN-LAST:event_listVariableValueChanged

    private void btnSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSumActionPerformed

    private void btnProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductActionPerformed
        txtDisplayOp.setText(txtDisplayOp.getText() + '*');
    }//GEN-LAST:event_btnProductActionPerformed

    private void JCFunctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCFunctionActionPerformed
       
        if (JCFunction.getSelectedIndex() == 0){
            //int exponent = Integer.parseInt(JOptionPane.showInputDialog("Please insert your exponent"));
           txtDisplayOp.setText("∫ x^");
            btnIntegral.setEnabled(false);
            btnSubstract.setEnabled(false);
            btnDivide.setEnabled(false);
            btnProduct.setEnabled(false);
            btnExponent.setEnabled(false);
            btnSum.setEnabled(false);
            btnRoot.setEnabled(false);
        }
        if (JCFunction.getSelectedIndex() == 1){
            
        }
        
    }//GEN-LAST:event_JCFunctionActionPerformed

    private void btnCloseOperatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseOperatorActionPerformed
        
    }//GEN-LAST:event_btnCloseOperatorActionPerformed

    private void btnOneNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneNActionPerformed
        txtDisplay.setText(txtDisplay.getText() + '1');
    }//GEN-LAST:event_btnOneNActionPerformed

    private void btnTwoNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoNActionPerformed
        txtDisplay.setText(txtDisplay.getText() + '2');
    }//GEN-LAST:event_btnTwoNActionPerformed

    private void btnFourNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFourNActionPerformed
    txtDisplay.setText(txtDisplay.getText() + '4');
    }//GEN-LAST:event_btnFourNActionPerformed

    private void btnFiveNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiveNActionPerformed
    txtDisplay.setText(txtDisplay.getText() + '5');
    }//GEN-LAST:event_btnFiveNActionPerformed

    private void btnSixNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSixNActionPerformed
    txtDisplay.setText(txtDisplay.getText() + '6');
    }//GEN-LAST:event_btnSixNActionPerformed

    private void btnSevenNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSevenNActionPerformed
    txtDisplay.setText(txtDisplay.getText() + '7');
    }//GEN-LAST:event_btnSevenNActionPerformed

    private void btnEightNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEightNActionPerformed
    txtDisplay.setText(txtDisplay.getText() + '8');
    }//GEN-LAST:event_btnEightNActionPerformed

    private void btnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroActionPerformed
    txtDisplay.setText(txtDisplay.getText() + '0');
    }//GEN-LAST:event_btnZeroActionPerformed

    private void btnNineN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNineN1ActionPerformed
    txtDisplay.setText(txtDisplay.getText() + '9');
    }//GEN-LAST:event_btnNineN1ActionPerformed

    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed
        newOperation.setExponent(Integer.parseInt(txtDisplay.getText()));
        newOperation.getExponent();
    }//GEN-LAST:event_btnEqualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox JCFunction;
    private javax.swing.JButton btnCloseOperator;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnEightN;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnExponent;
    private javax.swing.JButton btnFiveN;
    private javax.swing.JButton btnFourN;
    private javax.swing.JButton btnIntegral;
    private javax.swing.JButton btnNineN1;
    private javax.swing.JButton btnOneN;
    private javax.swing.JButton btnProduct;
    private javax.swing.JButton btnRoot;
    private javax.swing.JButton btnSevenN;
    private javax.swing.JButton btnSixN;
    private javax.swing.JButton btnSubstract;
    private javax.swing.JButton btnSum;
    private javax.swing.JButton btnThreeN1;
    private javax.swing.JButton btnTwoN;
    private javax.swing.JButton btnZero;
    private javax.swing.JList listVariable;
    private javax.swing.JTextField txtDisplay;
    private javax.swing.JTextField txtDisplayOp;
    // End of variables declaration//GEN-END:variables
}
